import type { Dispatch, MutableRefObject, SetStateAction } from "react";

type AdminActionOptions = {
  busy?: string;
  success?: (response: any) => string;
  after?: (response: any) => void;
};

export type AdminResourceContext = {
  actionData: any;
  adminNote: string;
  approvalDecisions: Record<string, any>;
  busyAction: string;
  contentAnnouncementCreating: boolean;
  contentAnnouncementData: any;
  contentAnnouncementError: string | null;
  contentAnnouncementId: string;
  contentAnnouncementLoading: boolean;
  contentCreating: boolean;
  contentExpandedIds: Set<string>;
  contentTab: "developer_contact" | "developer_log" | "help" | "announcements";
  contentTreeQuery: string;
  courseDraft: Record<string, string>;
  courseEditorRef: MutableRefObject<HTMLDivElement | null>;
  coursePage: number;
  courseQuery: string;
  courseSourceFilter: string;
  courseStatusFilter: string;
  courseTagFilter: string;
  data: any;
  errorEventQuery: string;
  importEdit: any;
  importPage: number;
  importPreviewTab: string;
  importSearch: string;
  loadCourseImportPreview: (importBatchId: string) => Promise<void>;
  openCourseEditor: (course: any) => void;
  primaryRows: any[];
  resource: string;
  role: string;
  rows: Array<[string, any[]]>;
  runAction: (path: string, method: string, body: Record<string, unknown>, options?: AdminActionOptions) => Promise<any>;
  selectedCourse: any;
  selectedId: string;
  selectedLabel: (row: any) => string;
  setAdminNote: Dispatch<SetStateAction<string>>;
  setApprovalDecisions: Dispatch<SetStateAction<Record<string, any>>>;
  setContentAnnouncementCreating: Dispatch<SetStateAction<boolean>>;
  setContentAnnouncementId: Dispatch<SetStateAction<string>>;
  setContentCreating: Dispatch<SetStateAction<boolean>>;
  setContentExpandedIds: Dispatch<SetStateAction<Set<string>>>;
  setContentTab: Dispatch<SetStateAction<"developer_contact" | "developer_log" | "help" | "announcements">>;
  setContentTreeQuery: Dispatch<SetStateAction<string>>;
  setCourseDraft: Dispatch<SetStateAction<Record<string, string>>>;
  setCoursePage: Dispatch<SetStateAction<number>>;
  setCourseQuery: Dispatch<SetStateAction<string>>;
  setCourseSourceFilter: Dispatch<SetStateAction<string>>;
  setCourseStatusFilter: Dispatch<SetStateAction<string>>;
  setCourseTagFilter: Dispatch<SetStateAction<string>>;
  setErrorEventQuery: Dispatch<SetStateAction<string>>;
  setImportEdit: Dispatch<SetStateAction<any>>;
  setImportPage: Dispatch<SetStateAction<number>>;
  setImportPreviewTab: Dispatch<SetStateAction<string>>;
  setImportSearch: Dispatch<SetStateAction<string>>;
  setResult: Dispatch<SetStateAction<{ type: "success" | "error" | "info"; message: string } | null>>;
  setRole: Dispatch<SetStateAction<string>>;
  setSelectedId: Dispatch<SetStateAction<string>>;
  setStatus: Dispatch<SetStateAction<string>>;
  setTextFields: Dispatch<SetStateAction<Record<string, string>>>;
  setTicketCategoryFilter: Dispatch<SetStateAction<string>>;
  setTicketQuery: Dispatch<SetStateAction<string>>;
  setTicketStatusFilter: Dispatch<SetStateAction<string>>;
  startImportEdit: (row: any) => void;
  status: string;
  textFields: Record<string, string>;
  ticketCategoryFilter: string;
  ticketQuery: string;
  ticketStatusFilter: string;
  courseDraftPayload: (draft?: Record<string, string>) => Record<string, unknown>;
  coursePayloadFromRawJson: (rawJson: string) => Record<string, unknown>;
  courseRawJsonText: (draft?: Record<string, string>) => string;
  payloadForEditing: () => string;
  applyImportEdit: () => void;
};
