export const ERROR_CODES = {
  API_BAD_REQUEST: "API_BAD_REQUEST",
  API_UNAUTHORIZED: "API_UNAUTHORIZED",
  API_FORBIDDEN: "API_FORBIDDEN",
  API_NOT_FOUND: "API_NOT_FOUND",
  API_CONFLICT: "API_CONFLICT",
  API_RATE_LIMITED: "API_RATE_LIMITED",
  API_METHOD_NOT_ALLOWED: "API_METHOD_NOT_ALLOWED",
  API_SYSTEM_PAUSED: "API_SYSTEM_PAUSED",
  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",

  AUTH_VERIFICATION_COOLDOWN: "AUTH_VERIFICATION_COOLDOWN",
  AUTH_VERIFICATION_INVALID: "AUTH_VERIFICATION_INVALID",
  AUTH_LOGIN_INVALID_CREDENTIALS: "AUTH_LOGIN_INVALID_CREDENTIALS",
  AUTH_LOGIN_RATE_LIMIT: "AUTH_LOGIN_RATE_LIMIT",
  AUTH_ADMIN_LOGIN_REQUIRED: "AUTH_ADMIN_LOGIN_REQUIRED",
  AUTH_ADMIN_LOGIN_INVALID: "AUTH_ADMIN_LOGIN_INVALID",
  AUTH_ACCOUNT_RESTRICTED: "AUTH_ACCOUNT_RESTRICTED",

  COURSE_IMPORT_INVALID_JSON: "COURSE_IMPORT_INVALID_JSON",
  COURSE_IMPORT_DUPLICATE_PENDING: "COURSE_IMPORT_DUPLICATE_PENDING",
  COURSE_OFFERING_INVALID: "COURSE_OFFERING_INVALID",
  COURSE_MERGE_INVALID: "COURSE_MERGE_INVALID",

  CHECKPOINT_NOT_FOUND: "CHECKPOINT_NOT_FOUND",
  CHECKPOINT_RESTORE_FAILED: "CHECKPOINT_RESTORE_FAILED",

  UPLOAD_FILE_REQUIRED: "UPLOAD_FILE_REQUIRED",
  UPLOAD_FILE_TOO_LARGE: "UPLOAD_FILE_TOO_LARGE",
  UPLOAD_EXTENSION_BLOCKED: "UPLOAD_EXTENSION_BLOCKED",
  UPLOAD_MIME_MISMATCH: "UPLOAD_MIME_MISMATCH",
  UPLOAD_STORAGE_FAILED: "UPLOAD_STORAGE_FAILED",

  TEAMUP_INVALID_TRANSITION: "TEAMUP_INVALID_TRANSITION",
  SUPPORT_TICKET_INVALID: "SUPPORT_TICKET_INVALID"
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];

export function errorCodeForStatus(status: number): ErrorCode {
  if (status === 400) return ERROR_CODES.API_BAD_REQUEST;
  if (status === 401) return ERROR_CODES.API_UNAUTHORIZED;
  if (status === 403) return ERROR_CODES.API_FORBIDDEN;
  if (status === 404) return ERROR_CODES.API_NOT_FOUND;
  if (status === 405) return ERROR_CODES.API_METHOD_NOT_ALLOWED;
  if (status === 409) return ERROR_CODES.API_CONFLICT;
  if (status === 429) return ERROR_CODES.API_RATE_LIMITED;
  if (status === 503) return ERROR_CODES.API_SYSTEM_PAUSED;
  return ERROR_CODES.INTERNAL_SERVER_ERROR;
}

export const userFacingErrorMessage = "请求未能完成，请记录报错代码后反馈给管理员。";
